# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='texto',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
