# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmang', '0003_empleado_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
